import Avatar from '../images/avatar.png';
import Banner from '../images/banner.jpg';
import Background from '../images/background.jpg';
import DataBalk from '../images/databalk.png';
import Google from '../images/google.svg';
import HeaderIcon from '../images/headerIcon.png';
import HeaderText from '../images/headerText.png';
import First from '../images/subMenu/first.png';
import Second from '../images/subMenu/second.png';
import Third from '../images/subMenu/third.png';
import Fourth from '../images/subMenu/fourth.png';
import Nieubouw from '../images/nieubouw.png';
import React from '../images/react.png';
import ActueelOne from '../images/actueel1.png';
import ActueelTwo from '../images/actueel2.png';
import ActueelThree from '../images/actueel3.png';

export const AvatarImage = Avatar;
export const BannerImage = Banner;
export const BackgroundImage  = Background;
export const DataBalkImage = DataBalk;
export const GoogleImage = Google;
export const HeaderIconImage  = HeaderIcon;
export const HeaderTextImage = HeaderText;
export const FirstImage  = First;
export const SecondImage = Second;
export const ThirdImage = Third;
export const FourthImage = Fourth;
export const NieubouwImage = Nieubouw;
export const ReactImage = React;
export const ActueelOneImage = ActueelOne;
export const ActueelTwoImage = ActueelTwo;
export const ActueelThreeImage = ActueelThree;